name: Python Lint PyCodeStyle

on:
  push:
    branches:
      - main    # Run this on push to the main branch
  pull_request:
    branches:
      - main    # Run this on pull requests to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Set your required Python version

    - name: Install pycodestyle
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle

    - name: Run pycodestyle
      run: pycodestyle *.py  # This will check all the Python files in the repo

    # Optionally, you can fail the workflow if pycodestyle detects any issues
    - name: Check for pycodestyle issues
      run: |
        pycodestyle . --count --max-line-length=79 --statistics
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "Pycodestyle found issues in the code."
          exit 1
        fi
